module.exports = {
    corsOptions: {
        origin: [
            "http://localhost:8080",
            "http://localhost:8080/",
            "http://localhost:8888/",
            "http://localhost:8888",
            "http://super.localhost:8888/",
            "http://super.localhost:8888",
            "http://team.localhost:8888/",
            "http://team.localhost:8888",
            "http://admin.localhost:8888/",
            "http://admin.localhost:8888",
            "https://super.prakriti.one/",
            "https://admin.prakriti.one/",
            "https://team.prakriti.one/",
            "https://prakriti.one/",
            "https://www.prakriti.one/",
            "https://super.prakriti.one",
            "https://admin.prakriti.one",
            "https://team.prakriti.one",
            "https://prakriti.one",
            "https://www.prakriti.one",
            "https://test.prakriti.one/",
	        "https://test.prakriti.one",
	        "http://test.prakriti.one",
            "https://super.test.prakriti.one",
		    "https://super.test.prakriti.one/",
            "https://super.test.prakriti.one",
            "https://admin.test.prakriti.one",
            "https://team.test.prakriti.one",
		"https://dev.super.prakriti.one/",
		"https://dev.admin.prakriti.one/",
		"https://dev.team.prakriti.one/",
		"https://dev.prakriti.one",
		"https://dev.super.prakriti.one",
		"https://dev.admin.prakriti.one",
		"https://dev.team.prakriti.one",

        ]
    }
};
